DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS type_size_gender CASCADE;
DROP TABLE IF EXISTS clothing_size CASCADE;
DROP TABLE IF EXISTS color CASCADE;
DROP TABLE IF EXISTS product_subtype CASCADE;
DROP TABLE IF EXISTS product_type CASCADE;
DROP TABLE IF EXISTS gender CASCADE;